#!/usr/bin/env bash
#Displays "Best School" 10 times and displays "HI" on the 9th iteration

i=0

while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
