#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hours=0
minutes=1

while [ $hours -lt 13 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
done
