#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hours=0
minutes=1

while [ $hours -le 12 ]
do
	while [ $minutes -le 59 ]
	do
		printf "%02d:%02d\n" $hours $minutes
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
	minutes=0
done
